module.exports = {
    extends: 'stylelint-config-standard',
    rules: {
        'at-rule-empty-line-before': null,
        'at-rule-no-unknown': null,
        'block-closing-brace-empty-line-before': null,
        'block-opening-brace-space-before': null,
        'comment-empty-line-before': null,
        'declaration-block-no-duplicate-properties': null,
        'declaration-block-no-redundant-longhand-properties': null,
        'declaration-block-semicolon-newline-after': null,
        'declaration-colon-newline-after': null,
        'declaration-colon-space-after': null,
        'declaration-empty-line-before': null,
        'font-family-name-quotes': null,
        'function-comma-newline-after': null,
        'function-comma-space-after': null,
        'function-url-quotes': null,
        'max-empty-lines': null,
        'number-leading-zero': null,
        'rule-empty-line-before': null,
        'selector-list-comma-newline-after': null,
        'selector-max-specificity': '0,6,0',
        'selector-pseudo-element-colon-notation': 'single',
        'string-quotes': null,
        'indentation': null,
        'no-duplicate-selectors': null,
        'no-descending-specificity': null,
        'selector-class-pattern': null,
        'max-line-length': null
    }
};
